// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:c20c13ca-9c62-4f87-8376-59a7a9621b8e",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_nYFT7v1hQ",
  "aws_user_pools_web_client_id": "3heaviig8pvc2b6u611lbub8t",
  "oauth": {},
  "aws_dynamodb_all_tables_region": "us-east-1",
  "aws_dynamodb_table_schemas": [
    {
      "tableName": "events-prod",
      "region": "us-east-1"
    }
  ],
  "aws_cloud_logic_custom": [
    {
      "name": "events",
      "endpoint": "https://7fhgyy03p7.execute-api.us-east-1.amazonaws.com/prod",
      "region": "us-east-1"
    }
  ]
};


export default awsmobile;