// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:dbe07176-613f-4324-a396-d259917d20c4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_WMdmf9TDw",
    "aws_user_pools_web_client_id": "66r3tnuff455tasdk387b6a4jk",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "events",
            "region": "us-west-2"
        },
        {
            "tableName": "resources",
            "region": "us-west-2"
        },
        {
            "tableName": "profiles",
            "region": "us-west-2"
        },
        {
            "tableName": "payments",
            "region": "us-west-2"
        },
        {
            "tableName": "apprenticeship",
            "region": "us-west-2"
        },
        {
            "tableName": "product",
            "region": "us-west-2"
        },
        {
            "tableName": "experience",
            "region": "us-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "eventscrud",
            "endpoint": "https://s3pxbz9b92.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        },
        {
            "name": "resources",
            "endpoint": "https://brd5q5r2o9.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        },
        {
            "name": "profile",
            "endpoint": "https://bxgjapi33a.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        },
        {
            "name": "payments",
            "endpoint": "https://hhx1hn5n2j.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        },
        {
            "name": "apprenticeship",
            "endpoint": "https://ep8jootcg2.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        },
        {
            "name": "product",
            "endpoint": "https://1mbybqgs4l.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        },
        {
            "name": "queue",
            "endpoint": "https://96u8dfy05c.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
