// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9fe677d7-a799-4e10-a442-f1beeff21731",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_d4BELL8OK",
    "aws_user_pools_web_client_id": "67efmh82veodju1sjfp80q0tgi",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "events",
            "region": "us-west-2"
        },
        {
            "tableName": "payments",
            "region": "us-west-2"
        },
        {
            "tableName": "resources",
            "region": "us-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "events",
            "endpoint": "https://x5d788qn76.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        },
        {
            "name": "payments",
            "endpoint": "https://tqddwul5th.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        },
        {
            "name": "resources",
            "endpoint": "https://84xd1scx8f.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
