const mongoose = require('mongoose');
const ExperienceSchema = new mongoose.Schema({
  id: String,
  xp: Number,
  xpEarned: Number,
  achievements: Number,
  memberId: String,  
  type: String,
  approved: Boolean,
  title: String,
  description: String,
  github: String,
  _1: Boolean,
  _1_approved: Boolean,
  _2: Boolean,
  _2_approved: Boolean,
  _3: Boolean,
  _3_approved: Boolean,
  _4: Boolean,
  _4_approved: Boolean,
  _5: Boolean,
  _5_approved: Boolean,
  _6: Boolean,
  _6_approved: Boolean,
  _7: Boolean,
  _7_approved: Boolean,
  _8: Boolean,
  _8_approved: Boolean,
  _9: Boolean,
  _9_approved: Boolean,
  _10: Boolean,
  _10_approved: Boolean,
  _11: Boolean,
  _11_approved: Boolean,
  _12: Boolean,
  _12_approved: Boolean,
  _13: Boolean,
  _13_approved: Boolean,
  _14: Boolean,
  _14_approved: Boolean,
  _15: Boolean,
  _15_approved: Boolean,
});
module.exports = mongoose.model('Experience', ExperienceSchema);