const mongoose = require('mongoose');
const ExperienceSchema = new mongoose.Schema({
  id: String,
  xp: Number,
  xpEarned: Number,
  achievements: Number,
  memberId: String,  
  type: String,
  approved: Boolean,
  title: String,
  description: String,
  github: String,
  _01: Boolean,
  _01_approved: Boolean,
  _02: Boolean,
  _02_approved: Boolean,
  _03: Boolean,
  _03_approved: Boolean,
  _04: Boolean,
  _04_approved: Boolean,
  _05: Boolean,
  _05_approved: Boolean,
  _06: Boolean,
  _06_approved: Boolean,
  _07: Boolean,
  _07_approved: Boolean,
  _08: Boolean,
  _08_approved: Boolean,
  _09: Boolean,
  _09_approved: Boolean,
  _10: Boolean,
  _10_approved: Boolean,
  _11: Boolean,
  _11_approved: Boolean,
  _12: Boolean,
  _12_approved: Boolean,
  _13: Boolean,
  _13_approved: Boolean,
  _14: Boolean,
  _14_approved: Boolean,
  _15: Boolean,
  _15_approved: Boolean,
});
module.exports = mongoose.model('Experience', ExperienceSchema);