const mongoose = require('mongoose');
const ExperienceSchema = new mongoose.Schema({
  id: String,
  xp: Number,
  xpEarned: Number,
  achievements: Number,
  memberId: String,  
  type: String,
  approved: Boolean,
  title: String,
  description: String,
  _1: BOOLEAN,
  _1_approved: BOOLEAN,
  _2: BOOLEAN,
  _2_approved: BOOLEAN,
  _3: BOOLEAN,
  _3_approved: BOOLEAN,
  _4: BOOLEAN,
  _4_approved: BOOLEAN,
  _5: BOOLEAN,
  _5_approved: BOOLEAN,
  _6: BOOLEAN,
  _6_approved: BOOLEAN,
  _7: BOOLEAN,
  _7_approved: BOOLEAN,
  _8: BOOLEAN,
  _8_approved: BOOLEAN,
  _9: BOOLEAN,
  _9_approved: BOOLEAN,
  _10: BOOLEAN,
  _10_approved: BOOLEAN,
  _11: BOOLEAN,
  _11_approved: BOOLEAN,
  _12: BOOLEAN,
  _12_approved: BOOLEAN,
  _13: BOOLEAN,
  _13_approved: BOOLEAN,
  _14: BOOLEAN,
  _14_approved: BOOLEAN,
  _15: BOOLEAN,
  _15_approved: BOOLEAN,
});
module.exports = mongoose.model('Experience', ExperienceSchema);